### ISSUE TITLE
optional flag to request short version of document

### ISSUE THREAD

**Issue by thomasheckmann** [thomasheckmann/zxinfo-services#10]
--> It could have another input parameter flag (or perhaps a different operation?) to request a shorter version of these results. The current result is too big to be handled by a client running directly from a retro machine (ZX Spectrum Next, ZX Uno, Chloe, etc). In shorter version, the result would be basically the same, except without the following fields: features, competition, majorclone, themedgroup, unsortedgroup, relatedsites, youtubelinks, magrefs, adverts, titlesuggest, authorsuggest, metadata_author.

--> Operation "/v2/search" should also have a similar input parameter flag (or perhaps a different operation?) to request a shorter version of these results, for the same reason.

**Comment by Blughes** [comment]
I would suggest having the compact/short version as the default option, if the user wants to retrieve more detailed info, it should be done as a separate call.

**Comment by thomasheckmann** [comment]
http://api.zxinfo.dk/doc/#!/zxinfo/getGameById
* ID check and padding if required
* Compact version by default
