### ISSUE TITLE
Search by publisher times out if no size or offset parameter is supplied

### ISSUE THREAD

**Issue by CatpainBlack** [thomasheckmann/zxinfo-services#6]
The documentation for GET /publishers/{publisher-name}/games states that the size and offset parameters are not required, but if you don't use them you get a 504 gateway timeout error.

**Comment by thomasheckmann** [comment]
Need to update documentation/swagger file.

**Comment by thomasheckmann** [comment]
Swagger documentation updated. Added a few default values as well, to get started quickly.
