### ISSUE TITLE
Cleanup JSON document

### ISSUE THREAD

**Issue by thomasheckmann** [thomasheckmann/zxinfo-services#8]
I wrote a small list of possible improvements for operation "/games/{game-id}", that should make it easier to use and provide more compact results, without loosing any information:

--> Field "alsoknownas" should be a list (certain games have multiple synonyms).

--> Perhaps it would be better to omit fields when value is null or empty?

--> Inside "releases", I suggest field "seq" should be renamed to "release". Its meaning will be more intuitive.

--> There's no need to "filename", since it's trivial to obtain it from "url".

--> There's no need for "groups", since you already have separate sets for each kind of group.

--> Inside "series", there's no need for "grouptype" (it will be always 'S' for series)

--> Inside "features", there's no need for "id" and "text" (they will be always 'F' and 'Feature' respectively).

--> Inside "themedgroup", there's no need for "id" and "text" (they will be always 'T' and 'Theme' respectively).

--> Inside "majorclone", there's no need for "id" and "text" (they will be always 'M' and 'Major Clone' respectively).

--> Inside "competition", there's no need for "id" and "text" (they will be always 'C' and 'Competition' respectively).

--> Field "unnamedgroup" should be renamed to "unsortedgroup". Also there's no need for "id" and "text" (they will be always 'U' and 'Unsorted Group' respectively).

--> Inside "relatedsites", it would be better to have field "link" instead of "link_mask" (with substrings like {e7} already expanded properly).

**Comment by Blughes** [comment]
I would like to suggest most of these should be information retrieved in a separate call to the API. Not everyone is going to want to use everything!

**Comment by thomasheckmann** [comment]
related to #10

**Comment by thomasheckmann** [comment]
--> Perhaps it would be better to omit fields when value is null or empty?
**compact mode will remove empty values (getGameById - done)**

--> Inside "releases", I suggest field "seq" should be renamed to "release". Its meaning will be more intuitive.
**releases.seq => releases.release**

--> There's no need to "filename", since it's trivial to obtain it from "url".
**filename removed from**
* releases.filename
* additionals.filename

**keep in "screens", as needed by zxinfo.dk**


--> There's no need for "groups", since you already have separate sets for each kind of group.
** groups removed**

--> Inside "series", there's no need for "grouptype" (it will be always 'S' for series)
** removed series.grouptype, added series.entry_id**
(for easier lookup)

--> Inside "features", there's no need for "id" and "text" (they will be always 'F' and 'Feature' respectively).
**removed id, text - F hardcoded in UI**

--> Inside "themedgroup", there's no need for "id" and "text" (they will be always 'T' and 'Theme' respectively).
**removed id, text - T hardcoded in UI**

--> Inside "majorclone", there's no need for "id" and "text" (they will be always 'M' and 'Major Clone' respectively).
removed id, text - M hardcoded in UI

--> Inside "competition", there's no need for "id" and "text" (they will be always 'C' and 'Competition' respectively).
**removed id, text - C hardcoded in UI**


--> Field "unnamedgroup" should be renamed to "unsortedgroup". Also there's no need for "id" and "text" (they will be always 'U' and 'Unsorted Group' respectively).
**removed id, text, renamed to unsortedgroup - C hardcoded in UI**

--> Inside "relatedsites", it would be better to have field "link" instead of "link_mask" (with substrings like {e7} already expanded properly).
**added link with expanded substrings
removed link_mask**
